version: '3.8'

services:
  vosk-service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./vosk-model-small-en-us-0.15:/app/vosk-model-small-en-us-0.15
      - ./test.wav:/app/test.wav
      - ./.chroma:/app/.chroma
    devices:
      - /dev/snd:/dev/snd
    environment:
      - PYTHONUNBUFFERED=1
    command: /app/entrypoint.sh
    networks:
      - vosk-network

networks:
  vosk-network:
    driver: bridge

volumes:
  chroma_data:
    driver: local 