version: '3.8'

services:
  vosk-service:
    image: htmmhmd/voice-command:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    volumes:
      - ./vosk-model-small-en-us:/app/vosk-model-small-en-us
      - ./.chroma:/app/.chroma
      - ./test:/app/test
      - ./src:/app/src
      - ./data:/app/data
    devices:
      - /dev/snd:/dev/snd
    environment:
      - PYTHONUNBUFFERED=1
    # command: /app/entrypoint.sh
    networks:
      - vosk-network
    tty: true
    stdin_open: true

networks:
  vosk-network:
    driver: bridge

volumes:
  chroma_data:
    driver: local 