# version: '3.8'

services:
  vosk-service:
    # image: htmmhmd/voice-command:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:5555"  # Expose ZMQ port
    volumes:
      # - ./vosk-model-small-en-us-0.15:/app/vosk-model-small-en-us 
      # - ./vosk-model:/app/vosk-model-small-en-us
      - ./.chroma:/app/.chroma
      - ./test:/app/test
      - ./src:/app/src
      - ./data:/app/data
      - /run/user/1000/pulse:/run/pulse:ro  # PulseAudio socket
      - /home/mona/.config/pulse/cookie:/root/.config/pulse/cookie:ro
      
    devices:
      - /dev/snd:/dev/snd
    environment:
      - PYTHONUNBUFFERED=1
      - PULSE_SERVER=unix:/run/pulse/native
      # - PULSE_COOKIE=/root/.config/pulse/cookie
    command: /app/entrypoint.sh
    networks:
      - vosk-network
    tty: true
    stdin_open: true

networks:
  vosk-network:
    driver: bridge

volumes:
  chroma_data:
    driver: local