version: '3.8'

services:
  vosk-service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./vosk-model-small-en-us-0.15:/app/vosk-model-small-en-us-0.15
      - ./test.wav:/app/test.wav
    devices:
      - /dev/snd:/dev/snd
    environment:
      - PYTHONUNBUFFERED=1
    command: python test_vosk_service.py
    networks:
      - vosk-network

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - ALLOW_RESET=true
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    networks:
      - vosk-network

networks:
  vosk-network:
    driver: bridge

volumes:
  chroma_data:
    driver: local 