name: Build and Push Docker Images
# Trigger the workflow on push to main branch, tag creation, or manual trigger

on:
    push:
      branches: [ master ]

# Define the job to build and push Docker images
jobs:
  build-streamer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
# Set up QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
# Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
# Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
# Build and push Docker images
      - name: Build and push to Docker HUB
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: ${{ github.event_name != 'pull_request' }}
          # For branch pushes, extract the branch name
          # For tag pushes, extract version from tag
          # Default version is 'latest'
          tags: | 
            ${{ secrets.DOCKERHUB_USERNAME }}/voice-command:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/voice-command:${{ github.ref_name }}
            ${{ secrets.DOCKERHUB_USERNAME }}/voice-command:latest
          build-args: |
              - BUILDKIT_INLINE_CACHE=1
              - BUILDKIT_PROGRESS=plain